version: 1.0.{build}
init: 
- ps: choco install docker-for-windows
build_script:
- ps: echo "Build with logging"
artifacts:
- path: '**\*.log'
  name: logs
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
